const heroSection={
    name:"herosection",
    type:"document",
    title:"heroSection",
    fields:[{
        name:"title",
        type:"string",
        title:"Title",
    },{
        name:"description",
        type:"string",
        title:"Description",
    },
    {
        name:"buttonText",
        type:"string",
        title:"ButtonText"
    },
    {
        name:"buttonLink",
        type:"string",
        title:"ButtonLink",
    },{
        name:"img",
        type:"image",
        title:"Img"
    }]
}
export default heroSection