import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Comforty",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body

        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="flex flex-col  text-gray-400">
          <div className="bg-[#272343] h-[45px] flex justify-between px-50  text-sm items-center" >
            <p className=" text-sm flex gap-x-2 items-end">
              <Image src={"/check.png"} alt="check" width={16} height={16} />Free shipping on all orders over $50
            </p>
            <div className="flex gap-x-2 ">

              <p>
                FAQs
              </p>
              <p>
                Need Help
              </p>
            </div>
          </div>
          <div className="bg-[#F0F2F3] h-[84px] flex  px-48 items-center justify-between">
            <div className="flex gap-x-2">
              <Image src={"/sofa.png"} alt="Sofa" width={40} height={40}></Image>
              <h1 className="text-[32px] text-black font-[inter] font-[500]">Comforty</h1>
            </div>
            <div className="w-30 bg-[#FFFFFF]  px-4 items-center flex gap-x-2 h-10 rounded-xl">
              <Image src={"/cart.png"} alt="cart" width={22} height={22} />
              <p className="text-[#272343] text-center font-[inter] text-sm">Cart</p>
            </div>
          </div>
          <nav className="h-[74px] bg-[#FFFFFF] flex justify-between px-48 items-center border-b border-b-gray-200">
            <ul className="flex text-[#636270] font-[inter] text-sm gap-x-8 ">
              <li>Home</li>
              <li>Shop</li>
              <li>Product</li>
              <li>Pages</li>
              <li>About</li>
            </ul>
            <div className="flex gap-x-2">
              <p>
                Contact:
              </p>
              <p className="text-[#272343]">

                (808) 555-0111
              </p>
            </div>
          </nav>
        </header>
        {children}
        <footer className="border-t border-t-gray-300 max-w-full ">
          <section className="max-w-[1150px]  h-[343px] flex space-x-10 px-48 py-20">
            <section className="">
              <div className="flex gap-x-4 items-center pt-1.5">
                <Image src={"/sofa.png"} alt="sofa" width={40} height={40} />
                <h1 className="text-2xl font-[inter] font-[600]">Comforty</h1>
              </div>
              <p className="w-80 text-[#272343] my-6">Vivamus tristique odio sit amet velit semper, eu posuere turpis interdum.
                Cras egestas purus
                <span className="flex gap-x-6 my-6">
                  <Image src={"/Facebook---Negative 2.png"} alt={"facebook"} width={16} height={16} className="hover:rounded-full hover:cursor-pointer hover:border-1 hover:border-[#007580]" />
                  <Image src={"/Twitter---Negative 1.png"} alt={"Twitter"} width={16} height={16} className="hover:rounded-full hover:cursor-pointer hover:border hover:border-[#007580]" />
                  <Image src={"/Instagram 1.png"} alt={"Instagram"} width={16} height={16} className="hover:rounded-full hover:cursor-pointer hover:border hover:border-[#007580]" />
                  <Image src={"/Pinterest---Negative 1.png"} alt={"Pinterest"} width={16} height={16} className="hover:rounded-full hover:cursor-pointer hover:border hover:border-[#007580]" />
                  <Image src={"/Youtube---Negative 1.png"} alt={"/Youtube"} width={16} height={16} className="hover:rounded-full hover:cursor-pointer hover:border hover:border-[#007580]" />
                </span>
              </p>
            </section>
          <section className="">
            <h1 className="font-[inter] text-sm text-[#9A9CAA] uppercase">
              Category
            </h1>
            <ul className="font-[inter] text-base text-[#272343] py-4 space-y-3  whitespace-nowrap w-max">
              <li className="hover:underline hover:text-[#007580] hover:cursor-pointer">Sofa</li>
              <li className="hover:underline hover:text-[#007580] hover:cursor-pointer">ArmChair</li>
              <li className="hover:underline hover:text-[#007580] hover:cursor-pointer">Wing Chair</li>
              <li className="hover:underline hover:text-[#007580] hover:cursor-pointer">Desk Chair</li>
              <li className="hover:underline hover:text-[#007580] hover:cursor-pointer">Wooden Chair</li>
              <li className="hover:underline hover:text-[#007580] hover:cursor-pointer">Park Chair</li>
            </ul>
          </section>
          <section className="">
            <h1 className="text-[#9A9CAA] font-[inter] text-sm uppercase">
              Support
            </h1>
            <ul className="text-base text-[#272343] font-[inter] font-[400] whitespace-nowrap w-max space-y-3 py-4">
              <li className="hover:underline hover:text-[#007580] hover:cursor-pointer">Help & Support</li>
              <li className="hover:underline hover:text-[#007580] hover:cursor-pointer">Terms & Conditions</li>
              <li className="hover:underline hover:text-[#007580] hover:cursor-pointer">Privacy Policy</li>
              <li className="hover:underline hover:text-[#007580] hover:cursor-pointer">Help</li>
            </ul>
          </section>
          <section className="">
            <h1 className="uppercase text-[#9A9CAA] text-sm">Newsletter</h1>
            <form className="py-8 flex gap-x-2">
              <input type="email" placeholder="Your Email" className="w-2xs h-11 border border-[#E1E3E5] rounded-lg p-3 text-base text-[#9A9CAA] "/>
                <button type="submit" className="w-28 h-11 bg-[#029FAE] text-[#FFFFFF] text-base rounded-lg hover:cursor-pointer hover:scale-105">Subscribe</button>
            </form>
            <p className="text-[#272343] text-[15px] font-[inter]">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam tincidunt erat enim.</p>
          </section>
          </section>
          <section className="h-20 flex  border-t  border-t-gray-300 w-full justify-between py-10 px-48 items-center">
            <p className="text-[#9A9CAA] font-[inter] text-sm">
              @ 2025 - Blogy - Designed & Develop by Saim
            </p>
            <span className="flex gap-x-2  items-center">
              <Image src={"/Group 11.png"} alt={"pic"} width={20}  height={20} className="w-5 h-5"/>
              <Image src={"/Group 12.png"} alt={"pic"} width={20} height={20} className="w-5 h-5"/>
              <Image src={"/Vector.png"} alt={"pic"} width={20} height={20} className="w-5 h-5"/>
              <Image src={"/Union.png"} alt={"pic"} width={20} height={20} className="w-5 h-5"/>

            </span>
 
          </section>
        </footer>
      </body>
    </html>
  );
}
