import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { cookies } from "next/headers";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Comforty",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
 const uid=(await cookies()).get("user_id")?.value
     if (!uid) {
   return (
         <h1>Error: Missing User ID</h1>
   );
 }
  return (
    <html lang="en">


      <body

className={`${geistSans.variable} ${geistMono.variable} antialiased`}
>
    


        {children}
      
      

      </body>

    </html>
  );
}
